### ISSUE TITLE
multiple definition errors when building with C++20

### ISSUE THREAD

**Issue by hanlet** [slac-epics-modules/ipmiComm#30]
I'm using C++20 and when linking the source files, there a numerous multiple definition errors due to defining variables in the header files.

**Comment by JJL772** [comment]
This should be fixed by #26. The underlying issue is `-fcommon` (default on old GCC) vs `-fno-common` (default on recent versions of GCC)

**Comment by hanlet** [comment]
Hi Jeremy, I fixed it, but haven't been successful in making a pull request.

Sent via the Samsung Galaxy S20 FE 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
